export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  DAMAGE_NOT_SEVERE: "DAMAGE_NOT_SEVERE",
  PLAN_ALREADY_EXISTS: "PLAN_ALREADY_EXISTS"
} as const;
